server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    url: jdbc:mysql://localhost:3306/mist?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: P@ssword1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities       #所有Entity别名类所在包